# Generated by Django 5.1.4 on 2024-12-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='conversation_history',
            field=models.TextField(default='[]'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
